module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      display: [
        'SF Pro Display',
        'Inter',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'sans-serif',
      ],
      text: [
        'SF Pro Text',
        'Inter',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'sans-serif',
      ],
      sans: [
        'SF Pro Text',
        'Inter',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'sans-serif',
      ],
    },
    fontSize: {
      xs: ['12px', { lineHeight: '16px', letterSpacing: '-0.01em' }],
      sm: ['14px', { lineHeight: '20px', letterSpacing: '-0.006em' }],
      base: ['17px', { lineHeight: '25px', letterSpacing: '-0.022em' }],
      lg: ['19px', { lineHeight: '25px', letterSpacing: '0.012em' }],
      xl: ['21px', { lineHeight: '29px', letterSpacing: '0.011em' }],
      '2xl': ['24px', { lineHeight: '32px', letterSpacing: '0.009em' }],
      '3xl': ['32px', { lineHeight: '40px', letterSpacing: '0.004em' }],
      '4xl': ['40px', { lineHeight: '44px', letterSpacing: '-0.009em' }],
      '5xl': ['48px', { lineHeight: '52px', letterSpacing: '-0.022em' }],
      '6xl': ['56px', { lineHeight: '60px', letterSpacing: '-0.022em' }],
      '7xl': ['64px', { lineHeight: '68px', letterSpacing: '-0.022em' }],
      '8xl': ['80px', { lineHeight: '84px', letterSpacing: '-0.022em' }],
    },
    extend: {
      colors: {
        // Apple Design System Colors
        apple: {
          blue: '#0071e3',
          'blue-dark': '#0077ed',
          'blue-light': '#2997ff',
          black: '#000000',
          white: '#ffffff',
          gray: {
            50: '#fafafa',
            100: '#f5f5f7',
            200: '#e8e8ed',
            300: '#d2d2d7',
            400: '#a1a1a6',
            500: '#86868b',
            600: '#6e6e73',
            700: '#515154',
            800: '#2c2c2e',
            900: '#1d1d1f',
          },
        },
        // Keep primary as Apple blue for compatibility
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#0071e3',
          600: '#0077ed',
          700: '#2563eb',
          800: '#1d4ed8',
          900: '#1e40af',
        },
        // Update gray to match Apple's design
        gray: {
          50: '#fafafa',
          100: '#f5f5f7',
          200: '#e8e8ed',
          300: '#d2d2d7',
          400: '#a1a1a6',
          500: '#86868b',
          600: '#6e6e73',
          700: '#515154',
          800: '#2c2c2e',
          900: '#1d1d1f',
        },
      },
      lineHeight: {
        hero: '4.5rem',
        tight: '1.08333',
        snug: '1.17647',
        normal: '1.47059',
      },
      letterSpacing: {
        tighter: '-0.022em',
        tight: '-0.009em',
        normal: '0em',
        wide: '0.011em',
        wider: '0.012em',
      },
      borderRadius: {
        apple: '12px',
        'apple-lg': '18px',
        'apple-xl': '24px',
      },
      boxShadow: {
        apple: '0 1px 4px rgba(0, 0, 0, 0.08)',
        'apple-lg': '0 2px 8px rgba(0, 0, 0, 0.12)',
        'apple-xl': '0 4px 16px rgba(0, 0, 0, 0.16)',
        'apple-blue': '0 2px 8px rgba(0, 113, 227, 0.25)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.8s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
    },
  },
  plugins: [],
};
